ASFLAGS_ADDITIONAL = -c -x assembler-with-cpp -MMD -mlongcalls -DESP_PLATFORM -DMBEDTLS_CONFIG_FILE="mbedtls/esp_config.h" -DHAVE_CONFIG_H -DGCC_NOT_5_2_0=0 -DWITH_POSIX -D_RUNONTARGETHARDWARE_BUILD_ -D_ROTH_ESP32_
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2022b/toolbox/target/SUPPOR~1/ARDUIN~1/registry/..
STACK_SIZE = 64
